apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fhesl1dlr-go 
  janus-idp.io/tekton: fhesl1dlr-go
  backstage.io/kubernetes-id: fhesl1dlr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fhesl1dlr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  