apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: fhesl1dlr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fhesl1dlr-go 
  name: fhesl1dlr-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fhesl1dlr-go
    weight: 100 
