apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fhesl1dlr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fhesl1dlr-go 
  name: fhesl1dlr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fhesl1dlr-go 
